include:
  # uncomment needed services
  - docker-compose-python-app.yml  # service app declared | depends on: db
  - docker-compose-flet-app.yml  # service flet declared | depends on: db
  - docker-compose-fastapi.yml  # service api declared | depends on: db
  - docker-compose-mariadb.yml  # services db, phpmyadmin, adminer, maxscale declared
  - docker-compose-node-red.yml  # service node-red
  - docker-compose-php-nginx.yml  # service php-nginx declared
  - docker-compose-portainer.yml  # service portainer declared
  - docker-compose-traefik.yml  # service traefik declared
  - docker-compose-mosquitto.yml # service mosquitto declared
  - docker-compose-api-mqtt-gateway.yml # service api-mqtt-gateway declared | depends on: mosquitto
  - docker-compose-influxdb-telegraf-grafana.yml # services influxdb, telegraf, grafana are declared
networks:
  backnet:
    name: back-network






