services:
  api-mqtt-gateway:
    build:
      context: ./backend/api-mqtt-gateway
      no_cache: true

    container_name: api-mqtt-gateway
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - PRODUCTION=True
      - PERSISTENT_CONFIG_FILENAME=settings_${PORT_API_MQTT_GATEWAY}.json
    # ports:
    #  - '${PORT_API_MQTT_GATEWAY}:${PORT_API_MQTT_GATEWAY}'
    volumes:
      - ./.api-mqtt-gateway:/usr/src/app/config
      - /etc/localtime:/etc/localtime
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-mqtt-gateway.rule=Host(`${SUBDOMAIN_API_MQTT_GATEWAY}${DOMAIN}`)"
      - "traefik.http.routers.api-mqtt-gateway.entrypoints=websecure"
      - "traefik.http.services.api-mqtt-gateway.loadbalancer.server.port=${PORT_API_MQTT_GATEWAY}"
      - "traefik.http.routers.api-mqtt-gateway.tls.certresolver=letsencrypt"
    networks:
      - backnet
    command:
      - /bin/sh
      - -c
      - |
        cd /usr/src/app
        uvicorn main:app ${RELOAD} --workers 1 --host "0.0.0.0" --port ${PORT_API_MQTT_GATEWAY} --proxy-headers
    depends_on:
      mosquitto:
        condition: service_healthy
