
# https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/

services:
  db:
    image: postgres
    restart: always
    environment:
      # default username = postgres
      POSTGRES_PASSWORD: example
    volumes:
      - ./.postgres/${DB_VOLUME_NAME}:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - backnet

  adminer:
    image: adminer
    restart: always
    ports:
      - "${PORT_ADMINER}:${PORT_ADMINER}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`${SUBDOMAIN_ADMINER}${DOMAIN}`)"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.tls.certresolver=letsencrypt"
      - "traefik.http.services.adminer.loadbalancer.server.port=${PORT_ADMINER}"
      - "traefik.http.routers.adminer.tls=true"
    networks:
      - backnet